services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - DB_PATH=/data/recommender.db
      - PORT=${PORT:-8080}
    volumes:
      - ./data:/data
    restart: unless-stopped
