name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: -E bodyclose,misspell,gosec,goconst,errorlint
      - name: Install gci
        run: go install github.com/daixiang0/gci@latest
      - name: Format imports
        run: gci write .
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -u
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: format imports with gci" && git push)
